run:
  tests: false # disable test files check

linters:
  enable:
    - deadcode
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck