name: docker-hub Pipeline

on:
  push:
    branches:
      - main

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: Run linter
        run: ~/go/bin/golangci-lint run
    
    if: ${{ always() }}  

  build_and_push:
  
    needs: lint
    if: ${{ needs.lint.result == 'success' }}

    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code  
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API image 
        uses: docker/build-push-action@v2
        with:
          context: ./task32_redis/api
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}/api:latest

      - name: Build and push UI image
        uses: docker/build-push-action@v2
        with:
          context: ./task20/web
          push: true
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}/webui:latest
