name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted, windows]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: false  # Disable submodule checkout
    
    - name: Start Minikube
      run: |
        minikube start

    - name: Create Secret
      run: |
        kubectl create secret generic postgres-secret `
        --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} `
        --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} `
        --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} `
        --from-literal=DB_HOST=${{ secrets.DB_HOST }} `
        --from-literal=DB_USER=${{ secrets.DB_USER }} `
        --from-literal=DB_PASS=${{ secrets.DB_PASS }} `
        --from-literal=DB_NAME=${{ secrets.DB_NAME }} `
        --from-literal=DB_PORT=${{ secrets.DB_PORT }} `
        --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} `
        --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      shell: powershell

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install fullstack ./task26_helm_cicd/fullstack --namespace default -v 3
      shell: bash
